apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: weather-service
  namespace: argocd
spec:
  project: weather-project
  source:
    repoURL: https://github.com/Nimrod-s-weather-app/weather-service.git
    targetRevision: master
    path: charts/weather-service
  destination:
    server: https://kubernetes.default.svc
    namespace: weather-services
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: weather-notifications-service
  namespace: argocd
spec:
  project: weather-project
  source:
    repoURL: https://github.com/Nimrod-s-weather-app/weather-notifications-service.git
    targetRevision: master
    path: charts/weather-notifications-service
  destination:
    server: https://kubernetes.default.svc
    namespace: weather-services
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
  namespace: argocd
spec:
  project: weather-project
  source:
    repoURL: https://github.com/Nimrod-s-weather-app/weather-infra.git
    targetRevision: main
    path: charts/kafka/templates
  destination:
    server: https://kubernetes.default.svc
    namespace: weather-infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zookeeper
  namespace: argocd
spec:
  project: weather-project
  source:
    repoURL: https://github.com/Nimrod-s-weather-app/weather-infra.git
    targetRevision: main
    path: charts/zookeeper/templates
  destination:
    server: https://kubernetes.default.svc
    namespace: weather-infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
